---
version: "3.6"
services:
  postgres:
    image: "postgres:11"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mailparser
    ports:
      - "5432:5432"
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
